[package]
name = "sdl2_mixer"
description = "SDL2_mixer bindings for Rust"
repository = "https://github.com/andelf/rust-sdl2_mixer"
version = "0.25.0"
license = "MIT/Apache-2.0"
authors = ["ShuYu Wang <andelf@gmail.com>"]
keywords = ["SDL", "windowing", "graphics", "music", "sound"]

[lib]
name = "sdl2_mixer"
path = "src/sdl2_mixer/lib.rs"

[dependencies]
bitflags = "0.6.0"
sdl2 = "0.27.0"
sdl2-sys = "0.27.0"
libc = "0.2"

# [dependencies.sdl2]
# git = "https://github.com/AngryLawyer/rust-sdl2"

# [dependencies.sdl2-sys]
# git = "https://github.com/AngryLawyer/rust-sdl2"
